spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB
  enabled: true
  file-size-threshold: 2KB
  location: /tmp/

findseat:
  data-path: C:\Users\mathias\Work\Projects\findseat2\target